version: "3.9"
   
services:
  db:
    container_name: lazy_django_project_starter_db
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file: ./config/dev.env
  web:
    container_name: lazy_django_project_starter_web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/code
    ports:
      - "8000:8000"
    env_file: ./config/dev.env
    depends_on:
      - db
